name: CI Process

on:
  push:
    branches: [ develop, 'release/*' ]
  pull_request:
    branches: [ develop, 'release/*' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # ─── Зөв байрлалтай defaults ──────────────────────
    defaults:
      run:
        working-directory: .    # root-д байгаа бол “.”; эсвэл "./calculator" бол тэнд зааж өгнө :contentReference[oaicite:4]{index=4}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkstyle Check
        run: mvn checkstyle:check

      - name: Run Tests & Coverage Check
        run: mvn test jacoco:check

      - name: Generate Coverage Report
        run: mvn jacoco:report
